n_listeners: 32  # more than we need, in case there are dismissals

snrs: [-4, -2, 0, 2]

block_len: 30

talkers: [NWF002,
          NWF003,
          NWF004,
          NWF008,
          NWF009,
          NWM001,
          NWM002,
          NWM004,
          NWM005,
          NWM007,
          NWF133,
          NWF135,
          NWF136,
          NWF137,
          NWF139,
          NWF140,
          NWF142,
          NWF143,
          NWF144,
          NWM055,
          NWM077,
          NWM078,
          NWM079,
          NWM080,
          NWM081,
          NWM082,
          NWM083,
          NWM084,
          NWM085,
          NWM086]

sentences: [01-07,
            02-01,
            02-06,
            03-10,
            04-02,
            04-04,
            04-05,
            04-08,
            05-02,
            05-05,
            05-07,
            06-01,
            06-04,
            06-05,
            06-09,
            06-10,
            07-08,
            07-09,
            07-10,
            08-04,
            08-07,
            10-06,
            10-09,
            10-10,
            11-05,
            11-07,
            12-03,
            12-10,
            13-01,
            13-03,
            13-07,
            14-04,
            14-06,
            15-06,
            15-07,
            15-09,
            16-01,
            16-02,
            17-03,
            17-05,
            17-06,
            18-01,
            18-02,
            18-04,
            18-05,
            18-06,
            19-02,
            19-06,
            19-07,
            19-10,
            20-04,
            22-01,
            22-02,
            22-03,
            22-04,
            22-06,
            22-07,
            23-01,
            23-07,
            23-08,
            23-09,
            24-02,
            24-07,
            24-09,
            25-01,
            25-02,
            25-04,
            26-09,
            27-06,
            27-07,
            27-09,
            28-01,
            28-08,
            30-02,
            30-04,
            30-06,
            31-03,
            31-04,
            31-10,
            32-09,
            33-01,
            33-05,
            33-08,
            34-01,
            34-02,
            34-05,
            34-06,
            34-08,
            34-10,
            36-01,
            36-08,
            36-10,
            37-01,
            37-05,
            37-09,
            08-02,
            16-10,
            22-08,
            31-01,
            38-02,
            47-01,
            56-07,
            65-03,
            39-01,
            39-04,
            39-10,
            40-06,
            40-07,
            40-09,
            40-10,
            41-02,
            41-08,
            41-09,
            42-09,
            44-10,
            45-01,
            45-02,
            45-05,
            45-08,
            45-10,
            46-02,
            46-05,
            47-04,
            48-01,
            48-03,
            49-05,
            49-08,
            50-01,
            50-06,
            51-04,
            51-06,
            52-07,
            52-10,
            53-01,
            53-03,
            53-09,
            55-01,
            55-02,
            55-04,
            55-07,
            56-02,
            56-08,
            56-09,
            56-10,
            57-02,
            57-06,
            57-09,
            58-03,
            58-08,
            59-04,
            59-05,
            60-03,
            60-07,
            60-09,
            60-10,
            61-09,
            62-06,
            63-05,
            64-05,
            64-06,
            65-08,
            65-09,
            66-01,
            66-05,
            67-01,
            67-05,
            67-06,
            67-09,
            67-10,
            68-02,
            68-08,
            70-02,
            70-04,
            70-06,
            70-09,
            71-05,
            71-06,
            71-08,
            72-05,
            72-06]
